/**
 * MockProvider — MegaAI's offline model simulator.
 *
 * Deterministic, dependency-free and instant: it reads the structured task
 * metadata agents attach to a completion request and answers in the action
 * protocol (`{ thoughts, summary, actions[] }`). This is what makes the whole
 * system runnable and testable with zero API keys; swap in real providers and
 * nothing else changes.
 */

import type {
  ActionRequest,
  CompletionRequest,
  CompletionResponse,
  ErrorCode,
  JsonObject,
  ModelCard,
  ProviderKind,
} from '@megaai/types';
import { MegaError } from '@megaai/types';
import { contentImageCount, contentText, estimateTokens, slugify } from '@megaai/utils';
import type { Provider } from '@megaai/contracts';
import { BUILTIN_MODELS } from '../models.js';

export interface MockProviderOptions {
  kind?: ProviderKind;
  name?: string;
  models?: ModelCard[];
  /** Throw RATE_LIMITED once more than this many requests have been served. */
  rateLimitAfter?: number;
  /** Always fail with this code (for fallback-chain tests). */
  alwaysFail?: ErrorCode;
}

interface FilePlan {
  path: string;
  content: string;
}

function codeFilesFor(title: string, description: string): FilePlan[] {
  const text = `${title} ${description}`.toLowerCase();
  const slug = slugify(title);
  const has = (...words: string[]) => words.some((word) => text.includes(word));

  if (has('setup', 'scaffold', 'init', 'skeleton', 'boilerplate')) {
    return [
      {
        path: 'package.json',
        content: `${JSON.stringify({ name: slug, version: '0.1.0', private: true, type: 'module', scripts: { start: 'node src/index.js', test: 'node --test "tests/**/*.test.js"' } }, null, 2)}\n`,
      },
      { path: 'src/index.js', content: `// Application entrypoint\nimport { createServer } from './server.js';\n\ncreateServer().listen(process.env.PORT ?? 3000);\nconsole.log('app started');\n` },
      { path: '.gitignore', content: 'node_modules/\n.env\n' },
    ];
  }
  if (has('database', 'schema', 'model', 'inventory')) {
    return [
      {
        path: 'src/db/schema.sql',
        content: `-- ${title}\nCREATE TABLE IF NOT EXISTS items (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  price_cents INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL\n);\n`,
      },
      {
        path: 'src/db/index.js',
        content: `// Minimal data-access layer for: ${title}\nconst rows = new Map();\n\nexport const db = {\n  put: (row) => rows.set(row.id, row),\n  get: (id) => rows.get(id),\n  all: () => [...rows.values()],\n};\n`,
      },
    ];
  }
  if (has('auth', 'login', 'signup', 'user account')) {
    return [
      {
        path: 'src/auth/auth.js',
        content: `// Authentication module for: ${title}\nconst sessions = new Map();\n\nexport function login(user, password) {\n  if (!user || !password) throw new Error('missing credentials');\n  const token = Math.random().toString(36).slice(2);\n  sessions.set(token, { user, at: Date.now() });\n  return token;\n}\n\nexport function verify(token) {\n  return sessions.has(token);\n}\n`,
      },
    ];
  }
  if (has('api', 'backend', 'server', 'endpoint', 'rest')) {
    return [
      {
        path: 'src/server.js',
        content: `// HTTP API for: ${title}\nimport http from 'node:http';\n\nexport function createServer() {\n  return http.createServer((req, res) => {\n    res.setHeader('content-type', 'application/json');\n    res.end(JSON.stringify({ ok: true, path: req.url }));\n  });\n}\n`,
      },
    ];
  }
  if (has('ui', 'frontend', 'page', 'storefront', 'catalog', 'design')) {
    return [
      {
        path: 'public/index.html',
        content: `<!doctype html>\n<meta charset="utf-8" />\n<title>${title}</title>\n<h1>${title}</h1>\n<p>Generated by MegaAI.</p>\n`,
      },
    ];
  }
  if (has('cart', 'checkout', 'payment', 'order')) {
    return [
      {
        path: `src/features/${slug}.js`,
        content: `// Feature: ${title}\nexport function ${slug.replace(/-/g, '_')}(input) {\n  return { ok: true, input };\n}\n`,
      },
    ];
  }
  return [
    {
      path: `src/modules/${slug}.js`,
      content: `// ${title}\n// ${description}\nexport function run() {\n  return '${slug} implemented';\n}\n`,
    },
  ];
}

/** Build the deterministic action-protocol reply for a task. */
function replyForTask(meta: JsonObject, request: CompletionRequest): JsonObject {
  const agentKind = String(meta.agentKind ?? 'generic');
  const title = String(meta.taskTitle ?? 'task');
  const description = String(meta.taskDescription ?? '');
  const slug = slugify(title);
  const actions: ActionRequest[] = [];
  let summary: string;

  switch (agentKind) {
    case 'coding': {
      const files = codeFilesFor(title, description);
      for (const file of files) {
        actions.push({ tool: 'fs.write', input: { path: file.path, content: file.content }, reason: title });
      }
      summary = `Implemented "${title}": wrote ${files.length} file(s) — ${files.map((f) => f.path).join(', ')}.`;
      break;
    }
    case 'testing': {
      const path = `tests/${slug}.test.js`;
      actions.push({
        tool: 'fs.write',
        input: {
          path,
          content: `import test from 'node:test';\nimport assert from 'node:assert';\n\ntest('${slug}', () => {\n  assert.ok(true, 'behaviour verified for: ${title}');\n});\n`,
        },
        reason: title,
      });
      if (meta.shellEnabled === true) {
        // Really execute the suite — expectSuccess makes a red run fail the
        // task. A glob (expanded by Node's own test runner) is used because
        // bare directory args are treated as entry files on Node 22.
        actions.push({
          tool: 'shell.exec',
          input: { command: 'node', args: ['--test', 'tests/**/*.test.js'], expectSuccess: true },
          reason: 'run the test suite for real',
        });
        summary = `Wrote tests for "${title}" and executed them with node --test — suite green.`;
      } else {
        summary = `Wrote tests for "${title}" (shell disabled here, so execution was skipped).`;
      }
      break;
    }
    case 'documentation': {
      actions.push({
        tool: 'fs.write',
        input: { path: `docs/${slug}.md`, content: `# ${title}\n\n${description || 'Documentation'}\n\n_Authored by the MegaAI documentation agent._\n` },
        reason: title,
      });
      summary = `Documented "${title}" in docs/${slug}.md.`;
      break;
    }
    case 'marketing': {
      actions.push({
        tool: 'fs.write',
        input: {
          path: `marketing/${slug}.md`,
          content: `# ${title}\n\nHeadline: Ship faster with an AI-run delivery team.\n\n- Benefit 1: one sentence in, working software out\n- Benefit 2: every step audited and recoverable\n- Call to action: try the demo today\n`,
        },
        reason: title,
      });
      summary = `Drafted marketing content for "${title}".`;
      break;
    }
    case 'devops': {
      actions.push({
        tool: 'fs.write',
        input: {
          path: 'DEPLOYMENT.md',
          content: `# Deployment plan\n\nTarget: ${title}\n\n1. Build artifacts\n2. Provision environment\n3. Deploy + smoke test\n4. Rollback plan: previous release kept warm\n`,
        },
        reason: title,
      });
      summary = `Prepared (simulated) deployment for "${title}".`;
      break;
    }
    case 'crm': {
      actions.push({
        tool: 'fs.write',
        input: { path: `crm/${slug}.md`, content: `# CRM update — ${title}\n\nStatus: progressed\nNext follow-up: scheduled\n` },
        reason: title,
      });
      summary = `Updated CRM records for "${title}".`;
      break;
    }
    case 'vision': {
      const imageCount = request.messages.reduce((sum, m) => sum + contentImageCount(m.content), 0);
      const content =
        imageCount > 0
          ? `# Vision analysis — ${title}\n\nImages inspected: ${imageCount}.\n\n${description || 'No further instructions given.'}\n\nFindings:\n- Image(s) received and decoded successfully.\n- No blocking visual defects detected by the offline analyzer.\n`
          : `# Vision analysis — ${title}\n\nNo images were attached to this task, so no visual analysis could be performed.\n`;
      actions.push({
        tool: 'fs.write',
        input: { path: `vision/${slug}-analysis.md`, content },
        reason: title,
      });
      summary =
        imageCount > 0
          ? `Analysed ${imageCount} image(s) for "${title}" and wrote findings to vision/${slug}-analysis.md.`
          : `"${title}": no images attached, nothing to analyse.`;
      break;
    }
    case 'ml-engineer': {
      const modelSlug = slug.replace(/-/g, '_');
      actions.push(
        {
          tool: 'fs.write',
          input: {
            path: `ml/${slug}/train.py`,
            content: `"""Training script for: ${title}\n${description}\n"""\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score\nimport joblib\nimport pandas as pd\n\n\ndef load_dataset(path="data.csv"):\n    return pd.read_csv(path)\n\n\ndef train(df):\n    X, y = df.drop(columns=["label"]), df["label"]\n    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n    model = RandomForestClassifier(n_estimators=200, random_state=42)\n    model.fit(X_train, y_train)\n    accuracy = accuracy_score(y_test, model.predict(X_test))\n    joblib.dump(model, "${modelSlug}.joblib")\n    return model, accuracy\n\n\nif __name__ == "__main__":\n    _, acc = train(load_dataset())\n    print(f"holdout accuracy: {acc:.4f}")\n`,
          },
          reason: title,
        },
        {
          tool: 'fs.write',
          input: {
            path: `ml/${slug}/MODEL_CARD.md`,
            content: `# Model card — ${title}\n\n${description || 'No description given.'}\n\n- Task type: classification (adjust to the real target)\n- Training data: data.csv (replace with the real dataset)\n- Algorithm: RandomForestClassifier (scikit-learn) — swap for a DL architecture (PyTorch/TensorFlow) if the task needs one\n- Evaluation: holdout accuracy, printed by train.py\n- Artifact: ${modelSlug}.joblib\n`,
          },
          reason: title,
        },
      );
      summary = `Scaffolded an ML training pipeline for "${title}": ml/${slug}/train.py, ml/${slug}/MODEL_CARD.md.`;
      break;
    }
    case 'research':
    case 'review':
    case 'architecture':
    default: {
      summary =
        agentKind === 'research'
          ? `Research on "${title}": summarised requirements, comparable products and constraints; no blockers found.`
          : agentKind === 'review'
            ? `Reviewed "${title}": code follows conventions; 0 blocking issues, 2 suggestions noted.`
            : `Completed "${title}".`;
      break;
    }
  }

  const imageCount = request.messages.reduce((sum, m) => sum + contentImageCount(m.content), 0);
  return {
    thoughts: `Deterministic mock reasoning for ${agentKind} task "${title}".`,
    summary,
    actions: actions as unknown as JsonObject['actions'],
    confidence: 0.9,
    echo: { promptChars: JSON.stringify(request.messages).length, images: imageCount },
  } as unknown as JsonObject;
}

export class MockProvider implements Provider {
  readonly kind: ProviderKind;
  readonly name: string;
  private readonly cards: ModelCard[];
  private readonly options: MockProviderOptions;
  private requestCount = 0;

  constructor(options: MockProviderOptions = {}) {
    this.kind = options.kind ?? 'mock';
    this.name = options.name ?? `${this.kind} provider (offline simulator)`;
    this.cards = options.models ?? BUILTIN_MODELS.filter((card) => card.provider === 'mock');
    this.options = options;
  }

  models(): ModelCard[] {
    return this.cards;
  }

  isConfigured(): boolean {
    return true;
  }

  requestsServed(): number {
    return this.requestCount;
  }

  async complete(request: CompletionRequest): Promise<CompletionResponse> {
    if (this.options.alwaysFail) {
      throw new MegaError(this.options.alwaysFail, `${this.kind} provider forced failure (${this.options.alwaysFail})`);
    }
    this.requestCount += 1;
    if (this.options.rateLimitAfter !== undefined && this.requestCount > this.options.rateLimitAfter) {
      throw new MegaError('RATE_LIMITED', `${this.kind} provider hit its simulated rate limit`);
    }

    const meta = request.metadata ?? {};
    const text =
      meta.agentKind !== undefined
        ? JSON.stringify(replyForTask(meta, request), null, 2)
        : JSON.stringify(
            {
              thoughts: 'No task metadata supplied; replying generically.',
              summary: `Acknowledged: ${contentText(request.messages.at(-1)?.content ?? '').slice(0, 120)}`,
              actions: [],
            },
            null,
            2,
          );

    const inputTokens = estimateTokens(
      `${request.system ?? ''}${request.messages.map((m) => contentText(m.content)).join('')}`,
    );
    return {
      text,
      provider: this.kind,
      model: request.model ?? this.cards[0]?.id ?? 'mock-frontier',
      stopReason: 'end_turn',
      usage: { inputTokens, outputTokens: estimateTokens(text) },
    };
  }
}
