/**
 * MockProvider — MegaAI's offline model simulator.
 *
 * Deterministic, dependency-free and instant: it reads the structured task
 * metadata agents attach to a completion request and answers in the action
 * protocol (`{ thoughts, summary, actions[] }`). This is what makes the whole
 * system runnable and testable with zero API keys; swap in real providers and
 * nothing else changes.
 */

import type {
  ActionRequest,
  CompletionRequest,
  CompletionResponse,
  ErrorCode,
  JsonObject,
  ModelCard,
  ProviderKind,
} from '@megaai/types';
import { MegaError } from '@megaai/types';
import { estimateTokens, slugify } from '@megaai/utils';
import type { Provider } from '@megaai/contracts';
import { BUILTIN_MODELS } from '../models.js';

export interface MockProviderOptions {
  kind?: ProviderKind;
  name?: string;
  models?: ModelCard[];
  /** Throw RATE_LIMITED once more than this many requests have been served. */
  rateLimitAfter?: number;
  /** Always fail with this code (for fallback-chain tests). */
  alwaysFail?: ErrorCode;
}

interface FilePlan {
  path: string;
  content: string;
}

function codeFilesFor(title: string, description: string): FilePlan[] {
  const text = `${title} ${description}`.toLowerCase();
  const slug = slugify(title);
  const has = (...words: string[]) => words.some((word) => text.includes(word));

  if (has('setup', 'scaffold', 'init', 'skeleton', 'boilerplate')) {
    return [
      {
        path: 'package.json',
        content: `${JSON.stringify({ name: slug, version: '0.1.0', private: true, type: 'module', scripts: { start: 'node src/index.js', test: 'node --test "tests/**/*.test.js"' } }, null, 2)}\n`,
      },
      { path: 'src/index.js', content: `// Application entrypoint\nimport { createServer } from './server.js';\n\ncreateServer().listen(process.env.PORT ?? 3000);\nconsole.log('app started');\n` },
      { path: '.gitignore', content: 'node_modules/\n.env\n' },
    ];
  }
  if (has('database', 'schema', 'model', 'inventory')) {
    return [
      {
        path: 'src/db/schema.sql',
        content: `-- ${title}\nCREATE TABLE IF NOT EXISTS items (\n  id TEXT PRIMARY KEY,\n  name TEXT NOT NULL,\n  price_cents INTEGER NOT NULL DEFAULT 0,\n  created_at TEXT NOT NULL\n);\n`,
      },
      {
        path: 'src/db/index.js',
        content: `// Minimal data-access layer for: ${title}\nconst rows = new Map();\n\nexport const db = {\n  put: (row) => rows.set(row.id, row),\n  get: (id) => rows.get(id),\n  all: () => [...rows.values()],\n};\n`,
      },
    ];
  }
  if (has('auth', 'login', 'signup', 'user account')) {
    return [
      {
        path: 'src/auth/auth.js',
        content: `// Authentication module for: ${title}\nconst sessions = new Map();\n\nexport function login(user, password) {\n  if (!user || !password) throw new Error('missing credentials');\n  const token = Math.random().toString(36).slice(2);\n  sessions.set(token, { user, at: Date.now() });\n  return token;\n}\n\nexport function verify(token) {\n  return sessions.has(token);\n}\n`,
      },
    ];
  }
  if (has('api', 'backend', 'server', 'endpoint', 'rest')) {
    return [
      {
        path: 'src/server.js',
        content: `// HTTP API for: ${title}\nimport http from 'node:http';\n\nexport function createServer() {\n  return http.createServer((req, res) => {\n    res.setHeader('content-type', 'application/json');\n    res.end(JSON.stringify({ ok: true, path: req.url }));\n  });\n}\n`,
      },
    ];
  }
  if (has('ui', 'frontend', 'page', 'storefront', 'catalog', 'design')) {
    return [
      {
        path: 'public/index.html',
        content: `<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8" />\n<meta name="viewport" content="width=device-width, initial-scale=1" />\n<title>${title}</title>\n<style>\n  body { font-family: system-ui, sans-serif; margin: 0; }\n  main { max-width: 100%; padding: 1rem; }\n  @media (min-width: 768px) { main { max-width: 60rem; margin: 0 auto; } }\n</style>\n</head>\n<body>\n<main>\n  <h1>${title}</h1>\n  <p>Generated by MegaAI.</p>\n  <button type="submit">Continue</button>\n</main>\n</body>\n</html>\n`,
      },
    ];
  }
  if (has('cart', 'checkout', 'payment', 'order')) {
    return [
      {
        path: `src/features/${slug}.js`,
        content: `// Feature: ${title}\nexport function ${slug.replace(/-/g, '_')}(input) {\n  return { ok: true, input };\n}\n`,
      },
    ];
  }
  return [
    {
      path: `src/modules/${slug}.js`,
      content: `// ${title}\n// ${description}\nexport function run() {\n  return '${slug} implemented';\n}\n`,
    },
  ];
}

/** Build the deterministic action-protocol reply for a task. */
function replyForTask(meta: JsonObject, request: CompletionRequest): JsonObject {
  const agentKind = String(meta.agentKind ?? 'generic');
  const title = String(meta.taskTitle ?? 'task');
  const description = String(meta.taskDescription ?? '');
  const slug = slugify(title);
  const actions: ActionRequest[] = [];
  let summary: string;

  switch (agentKind) {
    case 'coding': {
      const files = codeFilesFor(title, description);
      for (const file of files) {
        actions.push({ tool: 'fs.write', input: { path: file.path, content: file.content }, reason: title });
      }
      summary = `Implemented "${title}": wrote ${files.length} file(s) — ${files.map((f) => f.path).join(', ')}.`;
      break;
    }
    case 'testing': {
      const path = `tests/${slug}.test.js`;
      actions.push({
        tool: 'fs.write',
        input: {
          path,
          content: `import test from 'node:test';\nimport assert from 'node:assert';\n\ntest('${slug}', () => {\n  assert.ok(true, 'behaviour verified for: ${title}');\n});\n`,
        },
        reason: title,
      });
      if (meta.shellEnabled === true) {
        // Really execute the suite — expectSuccess makes a red run fail the
        // task. A glob (expanded by Node's own test runner) is used because
        // bare directory args are treated as entry files on Node 22.
        actions.push({
          tool: 'shell.exec',
          input: { command: 'node', args: ['--test', 'tests/**/*.test.js'], expectSuccess: true },
          reason: 'run the test suite for real',
        });
        summary = `Wrote tests for "${title}" and executed them with node --test — suite green.`;
      } else {
        summary = `Wrote tests for "${title}" (shell disabled here, so execution was skipped).`;
      }
      break;
    }
    case 'build': {
      if (meta.shellEnabled === true) {
        // Write a real, side-effect-free syntax checker and run it as a
        // pipeline step. It spawns `node --check` per file (parse only, no
        // execution), so a genuine syntax error fails the build task.
        actions.push({
          tool: 'fs.write',
          input: {
            path: 'build-check.mjs',
            content: `import { readdirSync, statSync } from 'node:fs';\nimport { join } from 'node:path';\nimport { spawnSync } from 'node:child_process';\n\nfunction walk(dir) {\n  const out = [];\n  for (const entry of readdirSync(dir)) {\n    if (entry === 'node_modules' || entry === '.git') continue;\n    const full = join(dir, entry);\n    if (statSync(full).isDirectory()) out.push(...walk(full));\n    else if (entry.endsWith('.js') || entry.endsWith('.mjs')) out.push(full);\n  }\n  return out;\n}\n\nlet failed = 0;\nfor (const file of walk('.')) {\n  const result = spawnSync(process.execPath, ['--check', file]);\n  if (result.status !== 0) {\n    failed += 1;\n    process.stderr.write('syntax error: ' + file + '\\n' + (result.stderr?.toString() ?? ''));\n  }\n}\nconsole.log('build-check: ' + (failed === 0 ? 'all files parse' : failed + ' file(s) failed'));\nprocess.exit(failed === 0 ? 0 : 1);\n`,
          },
          reason: 'build verification script',
        });
        actions.push({
          tool: 'pipeline.run',
          input: {
            steps: [{ name: 'syntax-check', command: 'node', args: ['build-check.mjs'] }],
          },
          reason: 'verify the project builds',
        });
        summary = `Verified the build for "${title}": every source file parses cleanly.`;
      } else {
        summary = `Build verification for "${title}" skipped (shell disabled in this environment).`;
      }
      break;
    }
    case 'documentation': {
      actions.push({
        tool: 'fs.write',
        input: { path: `docs/${slug}.md`, content: `# ${title}\n\n${description || 'Documentation'}\n\n_Authored by the MegaAI documentation agent._\n` },
        reason: title,
      });
      summary = `Documented "${title}" in docs/${slug}.md.`;
      break;
    }
    case 'marketing': {
      actions.push({
        tool: 'fs.write',
        input: {
          path: `marketing/${slug}.md`,
          content: `# ${title}\n\nHeadline: Ship faster with an AI-run delivery team.\n\n- Benefit 1: one sentence in, working software out\n- Benefit 2: every step audited and recoverable\n- Call to action: try the demo today\n`,
        },
        reason: title,
      });
      summary = `Drafted marketing content for "${title}".`;
      break;
    }
    case 'devops': {
      actions.push({
        tool: 'fs.write',
        input: {
          path: 'DEPLOYMENT.md',
          content: `# Deployment plan\n\nTarget: ${title}\n\n1. Build artifacts\n2. Provision environment\n3. Deploy + smoke test\n4. Rollback plan: previous release kept warm\n`,
        },
        reason: title,
      });
      actions.push({ tool: 'deploy.plan', input: {}, reason: 'describe the deployment' });
      // Approval-gated in policy; auto-resolves under autoApprove, otherwise
      // pauses for a human — exactly the intended deploy safety behaviour.
      actions.push({ tool: 'deploy.execute', input: {}, reason: 'deploy the delivery' });
      summary = `Prepared and deployed "${title}" (simulated target); URL recorded in .megaai-deploy.json.`;
      break;
    }
    case 'crm': {
      actions.push({
        tool: 'crm.client.upsert',
        input: { name: 'Client', email: 'client@example.com', status: 'active' },
        reason: 'record the client',
      });
      actions.push({
        tool: 'crm.activity.log',
        input: { client: 'client@example.com', kind: 'status', summary: title },
        reason: 'log project status',
      });
      actions.push({
        tool: 'fs.write',
        input: { path: `crm/${slug}.md`, content: `# CRM update — ${title}\n\nStatus: progressed\nNext follow-up: scheduled\n` },
        reason: title,
      });
      summary = `Updated CRM records for "${title}".`;
      break;
    }
    case 'support': {
      actions.push({
        tool: 'fs.write',
        input: { path: `support/${slug}.md`, content: `# Support note — ${title}\n\n${description || 'Client update'}\n` },
        reason: title,
      });
      actions.push({
        tool: 'comm.send',
        input: { to: 'client', subject: title, text: `Update on "${title}": completed and ready for your review.` },
        reason: 'notify the client',
      });
      summary = `Sent a client update for "${title}".`;
      break;
    }
    case 'browser': {
      // Pull a URL out of the task if present, else visit a synthetic page.
      const match = `${title} ${description}`.match(/https?:\/\/[^\s)]+/);
      const url = match?.[0] ?? 'https://example.com';
      actions.push({ tool: 'browser.fetch', input: { url }, reason: title });
      summary = `Browsed ${url} for "${title}" and captured its content.`;
      break;
    }
    case 'vision-testing': {
      actions.push({ tool: 'vision.audit', input: { file: 'public/index.html' }, reason: title });
      summary = `Ran visual + responsive testing on the built UI for "${title}".`;
      break;
    }
    case 'desktop': {
      actions.push({ tool: 'desktop.observe', input: { file: 'public/index.html' }, reason: title });
      summary = `Observed the UI and identified its interactive elements for "${title}".`;
      break;
    }
    case 'research':
    case 'review':
    case 'architecture':
    default: {
      summary =
        agentKind === 'research'
          ? `Research on "${title}": summarised requirements, comparable products and constraints; no blockers found.`
          : agentKind === 'review'
            ? `Reviewed "${title}": code follows conventions; 0 blocking issues, 2 suggestions noted.`
            : `Completed "${title}".`;
      break;
    }
  }

  return {
    thoughts: `Deterministic mock reasoning for ${agentKind} task "${title}".`,
    summary,
    actions: actions as unknown as JsonObject['actions'],
    confidence: 0.9,
    echo: { promptChars: JSON.stringify(request.messages).length },
  } as unknown as JsonObject;
}

/**
 * Deterministic stand-in for a model-generated plan. Shapes a valid PlanSpec
 * JSON so the meta brain's model-planning path is exercisable offline.
 */
function planReplyFor(goal: string): JsonObject {
  const spec = {
    projectName: goal.replace(/\s+/g, ' ').trim().slice(0, 60) || 'Model project',
    domain: 'model-generated',
    summary: `Model-generated plan for: ${goal.slice(0, 120)}`,
    phases: [
      {
        name: 'Discovery',
        tasks: [
          { title: 'Requirements research', description: `Clarify requirements for: ${goal}`, agentKind: 'research', complexity: 'standard' },
        ],
      },
      {
        name: 'Build',
        tasks: [
          { title: 'Project scaffold setup', description: 'Initialise the project skeleton', agentKind: 'coding', complexity: 'standard' },
          { title: 'Implement core functionality', description: goal, agentKind: 'coding', complexity: 'complex' },
        ],
      },
      {
        name: 'Quality',
        tasks: [
          { title: 'Build verification', description: 'Verify the project builds and parses', agentKind: 'build', complexity: 'standard' },
          { title: 'Automated test suite', description: 'Test the core functionality', agentKind: 'testing', complexity: 'standard' },
        ],
      },
      {
        name: 'Delivery',
        tasks: [
          { title: 'Project documentation', description: 'Document the deliverable', agentKind: 'documentation', complexity: 'trivial' },
          { title: 'Deployment preparation', description: 'Plan and run the deployment', agentKind: 'devops', complexity: 'standard' },
        ],
      },
    ],
    risks: ['Scope may grow as requirements are clarified'],
    questionsForHuman: [],
  };
  return spec as unknown as JsonObject;
}

export class MockProvider implements Provider {
  readonly kind: ProviderKind;
  readonly name: string;
  private readonly cards: ModelCard[];
  private readonly options: MockProviderOptions;
  private requestCount = 0;

  constructor(options: MockProviderOptions = {}) {
    this.kind = options.kind ?? 'mock';
    this.name = options.name ?? `${this.kind} provider (offline simulator)`;
    this.cards = options.models ?? BUILTIN_MODELS.filter((card) => card.provider === 'mock');
    this.options = options;
  }

  models(): ModelCard[] {
    return this.cards;
  }

  isConfigured(): boolean {
    return true;
  }

  requestsServed(): number {
    return this.requestCount;
  }

  async complete(request: CompletionRequest): Promise<CompletionResponse> {
    if (this.options.alwaysFail) {
      throw new MegaError(this.options.alwaysFail, `${this.kind} provider forced failure (${this.options.alwaysFail})`);
    }
    this.requestCount += 1;
    if (this.options.rateLimitAfter !== undefined && this.requestCount > this.options.rateLimitAfter) {
      throw new MegaError('RATE_LIMITED', `${this.kind} provider hit its simulated rate limit`);
    }

    const meta = request.metadata ?? {};
    const text =
      meta.planning === true
        ? JSON.stringify(planReplyFor(String(meta.goal ?? request.messages.at(-1)?.content ?? 'a project')), null, 2)
        : meta.agentKind !== undefined
          ? JSON.stringify(replyForTask(meta, request), null, 2)
          : JSON.stringify(
              {
                thoughts: 'No task metadata supplied; replying generically.',
                summary: `Acknowledged: ${request.messages.at(-1)?.content.slice(0, 120) ?? ''}`,
                actions: [],
              },
              null,
              2,
            );

    const inputTokens = estimateTokens(`${request.system ?? ''}${request.messages.map((m) => m.content).join('')}`);
    return {
      text,
      provider: this.kind,
      model: request.model ?? this.cards[0]?.id ?? 'mock-frontier',
      stopReason: 'end_turn',
      usage: { inputTokens, outputTokens: estimateTokens(text) },
    };
  }
}
